### ISSUE TITLE
scrollTo(y,x,animated) is deprecated

### ISSUE THREAD

**Issue by xpmike** [leecade/react-native-swiper#106] opened 2016-03-15 06:39 UTC
![20160315143715](https://cloud.githubusercontent.com/assets/1314128/13769557/728d7e76-eabb-11e5-9133-343fc5e04a43.png)

**Comment by lrettig** [comment] 2016-03-15 19:34
+1

**Comment by lrettig** [comment] 2016-03-15 19:35
This is a duplicate of https://github.com/leecade/react-native-swiper/issues/95

**Comment by Kennytian** [comment] 2016-03-17 11:10
+1

**Comment by xpmike** [comment] 2016-03-17 13:27
@lrettig tku for your remind

**Comment by Cspeisman** [comment] 2016-04-10 16:57
#113 will fix this issue. For a temporary fix change file locally and run `npm start` to build.

**Comment by rajkissu** [comment] 2016-05-08 11:41
Fixed in #112

**Closed by rajkissu** 2016-05-08 11:41 UTC
