### ISSUE TITLE
Swiper does not start at initial index, unless I set loop to false

### ISSUE THREAD

**Issue by thesubway** [leecade/react-native-swiper#527] opened 2017-08-18 16:51 UTC
### Which OS ?
iOS
### Version
Which versions are you using: React 16.0.0-alpha.12

- react-native-swiper v? 1.5.9
- react-native v0.?.? 0.46.0

### Expected behaviour
Upon launch, start at the first page

### Actual behaviour
Upon launch, starts at the last page

### How to reproduce it>

export default class App extends Component {
  constructor(props) {
    super(props);
    this.state = {
    };
  }
  render() {
    return (
      <Swiper index={0} style={styles.wrapper} showsButtons={true}>
        <Page1/>
        <Page2/>
        <Page3/>
      </Swiper>)
  }
}
AppRegistry.registerComponent('AwesomeProject', () => App);

### Steps to reproduce
1.Create App Component using the above code
2.Add styles variable from the README
3.Do not set the loop property

When I set Swiper loop={false}, there is no issue. In that case, it correctly starts at the initial page.

**Comment by dwilt** [comment] 2017-08-21 11:50
@thesubway I ran into this too. This is indeed a bug. Do you have `flex: 1` on the `Swiper` as a style? If so, try and remove it. That fixed it for me.

**Comment by arribbar** [comment] 2017-09-11 19:45
Do you still have the bug @thesubway ? 
If yes, can you fork the project and reproduce the bug? I have not enough time to do it on my own.
Thanks

**Comment by thesubway** [comment] 2017-09-12 05:58
Here is an example of my issue, reproduced, where page 2 shows up first:
https://github.com/thesubway/IssueTester

**Comment by jketcham** [comment] 2017-10-02 23:05
I'm also experiencing a variant of this issue, except on initial render the index is fine but on subsequent renders, the last slide is shown even though the index is still 0. Setting loop to false fixes this, so I imagine there's something wrong with how offset is calculated in relation to looping.

**Comment by arribbar** [comment] 2017-10-03 07:05
It looks like this is the same bug than #570.
Can you try again with the last version released yesterday, 1.5.13.
This PR https://github.com/leecade/react-native-swiper/pull/572 has been merged and should fixed this bug

**Closed** 2017-10-03 07:06 UTC

**Comment by bispul** [comment] 2017-10-12 02:08
its still not working on 1.5.13. does anyone have a fix ?

**Comment by hugweb** [comment] 2017-10-19 17:50
I don't know if it's exactly the same issue but when loop is set to TRUE and I reach the last slide : the old state is display (of the screen) before displaying the current one which create a glitch.

I think the problem is located in the updateIndex method and more particularly in the **setState** method.

```javascript
if (loopJump) {
      // when swiping to the beginning of a looping set for the third time,
      // the new offset will be the same as the last one set in state.
      // Setting the offset to the same thing will not do anything,
      // so we increment it by 1 then immediately set it to what it should be,
      // after render.
      if (offset[dir] === this.internals.offset[dir]) {
        newState.offset = { x: 0, y: 0 }
        newState.offset[dir] = offset[dir] + 1
        this.setState(newState, () => {                     <========== here
          this.setState({ offset: offset }, cb) 
        })
      } else {
        newState.offset = offset
        this.setState(newState, cb)
      }
    } else {
      this.setState(newState, cb)
    }
```

**Comment by dktan** [comment] 2017-11-01 21:47
**init offset is set in onLayout function, and onLayout is not called when view update**.
So, your problem was content loaded after page rendered, and all you layout was still set up as you have no children.
Quick work around: do not render swiper until all image loaded.

**Comment by windydang26** [comment] 2018-01-10 02:21
version 1.5.13 still not working. index changed to 0 but screen still is last screen.

**Comment by kevinEsherick** [comment] 2018-01-16 20:09
@windydang26 Still not working for me either. I have just set loop to false, since looping isn't critical for me, and that fixes it, but it would be nice if we could find the solution. I believe it only happens upon touch events in which setState is called, as someone hinted to previously. If at index 0, when setState is called it remains at index 0 but displays the content of the final index. It also prevents you from swiping right (looping back to the final index) when this occurs. Then when you swipe left it returns to the proper display of the 0 index. Maybe that helps someone better understand the problem, not sure. But if looping isn't critical then turning it off is an easy fix

**Comment by joelbowen** [comment] 2018-08-14 13:31
I think this issue should be re-opened. I am experiencing a similar issue:
- it shows my second page briefly, then goes to my first page

Setting loop to false resolves the issue, but certainly isn't ideal.

**Comment by byunghyunpark** [comment] 2018-09-10 05:43
I have the same bug  on 1.5.13 version

**Comment by klightsaber** [comment] 2018-11-02 07:14
> @thesubway I ran into this too. This is indeed a bug. Do you have `flex: 1` on the `Swiper` as a style? If so, try and remove it. That fixed it for me.

**Comment by Lelelo1** [comment] 2019-04-05 12:21
For me this issue occurs on second render. version 1.5.14. Doing something that triggers a render like pressing a button outside of this component makes it go from index 0 to last index.

**Comment by pgonzalez-santiago** [comment] 2019-05-28 10:23
Same here

**Comment by Cajeh** [comment] 2019-10-13 17:26
Same Here

**Comment by karmatobgyel** [comment] 2019-12-06 20:37
same here. 
on ios , it wont swipe left at the first swipe.

**Comment by alikianinejad** [comment] 2020-01-15 16:18
same here

**Comment by mattgilbertnet** [comment] 2020-07-31 22:42
same here

**Comment by reflexator** [comment] 2021-01-30 11:18
Anyone find solution for this?

**Comment by emp** [comment] 2022-09-12 19:07
on initialization, ```swiper.slideToLoop(0, 0)``` did it for me

React example, I want to only have a loop when I have more than one image:

```
useEffect(() => {
    if (swiperInstance && images.length > 1)
      swiperInstance.slideToLoop(0, 0)
  }, [images, swiperInstance]);
```

```
<Swiper loop={images.length > 1}>
```

**Comment by alan-automationworks** [comment] 2023-02-21 17:47
> on initialization, `swiper.slideToLoop(0, 0)` did it for me
> 
> React example, I want to only have a loop when I have more than one image:
> 
> ```
> useEffect(() => {
>     if (swiperInstance && images.length > 1)
>       swiperInstance.slideToLoop(0, 0)
>   }, [images, swiperInstance]);
> ```
> 
> ```
> <Swiper loop={images.length > 1}>
> ```

This worked for me, @emp. Thank you. But I'm wondering, is it not a bad idea to pass a `ref` to an `useEffect`?
